project: "habitat/builder-brigade"
repository: "github.com/habitat-sh/builder-brigade"
cloneURL: "https://github.com/habitat-sh/builder-brigade.git"
vcsSidecar: "deis/git-sidecar:latest"

# Advanced. You probably won't need to alter these.
allowPrivilegedJobs: "true"
github: {}
secrets: {}
kubernetes: {}
worker: {}
